from pathlib import Path

__all__ = [
    "CONFIG_PATH_ENV_NAME",
    "ACTIVE_MACHINE_CONFIG_KEY",
    "QUALIBRATE_CONFIG_KEY",
    "QUALIBRATE_PATH",
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_QUALIBRATE_CONFIG_FILENAME",
    "DEFAULT_ACTIVE_MACHINE_CONFIG_FILENAME",
    "QUALIBRATE_SETTINGS_ENV_PREFIX",
    "QUALIBRATE_STORAGE_SETTINGS_ENV_PREFIX",
    "ACTIVE_MACHINE_SETTINGS_ENV_PREFIX",
]
CONFIG_PATH_ENV_NAME = "QUALIBRATE_CONFIG_FILE"

ACTIVE_MACHINE_CONFIG_KEY = "active_machine"
QUALIBRATE_CONFIG_KEY = "qualibrate"

QUALIBRATE_PATH = Path().home() / ".qualibrate"
DEFAULT_CONFIG_FILENAME = "config.toml"
DEFAULT_QUALIBRATE_CONFIG_FILENAME = "qualibrate.toml"
DEFAULT_ACTIVE_MACHINE_CONFIG_FILENAME = "active_machine.toml"

QUALIBRATE_SETTINGS_ENV_PREFIX = "QUALIBRATE_"
QUALIBRATE_STORAGE_SETTINGS_ENV_PREFIX = "QUALIBRATE_STORAGE_"
ACTIVE_MACHINE_SETTINGS_ENV_PREFIX = "QUALIBRATE_ACTIVE_MACHINE_"
