name: Playwright Tests

on:
  pull_request:

jobs:
  test:
    uses: qua-platform/qualibrate-app/.github/workflows/reusable-playwright-tests.yaml@main
    with:
      qualibrate-config-ref: ${{ github.head_ref }}
    secrets: inherit