name: Create draft GitHub release

on:
  push:
    tags:
      - v*

jobs:
  build:
    uses: qua-platform/qualibrate-config/.github/workflows/reusable-build.yaml@main
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: python-package-*
          merge-multiple: true
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release create ${{ github.ref_name }}
          --notes-file notes.md
          --verify-tag --latest
          --draft
          "dist/qualibrate_config-${GITHUB_REF_NAME#v}-py3-none-any.whl"
          "dist/qualibrate_config-${GITHUB_REF_NAME#v}.tar.gz"
